#!/bin/bash

set -e

if [ -f /fabric.env ]; then
    . /fabric.env
fi

install() {
    # This script is executed once after the device is installed.

    # This is where you would download and install additional
    # packages.

    echo --- Temporarily switching to direct Internet access...
    ip route del default || true
    ip route add default via 192.168.0.254
    echo nameserver 8.8.8.8 > /etc/resolv.conf

    echo --- Waiting for Internet access...
    while ! ping -c 1 fortinet.com; do sleep 2; done    

    echo --- Installing packages...    
    apt update
    apt install -y sip-tester python3-click python3-selenium nano

    # Perform configuration restore
    restore
    # or execute a script
    script
}

script() {
    if [ ! -f /fabric.script ]; then
	return 0
    fi
    chmod +x /fabric.script
    /fabric.script
}

prepare() {
    # This script is executed every time before Fabric Studio backup
    # /fabric directory.

    # This is where you'd stop your services and copy the files you
    # want to backup from your system to /fabric directory.

    # Example:
    # service ldap stop
    # cp /etc/ldap/db /fabric/
    # service ldap start
    true
}

restore() {
    # This script is executed every time after Fabric Studio will
    # restore /fabric directory.

    echo --- Updating SSH configuration...
    cat /fabric/ssh/authorized_keys >> /root/.ssh/authorized_keys
    # Allow ssh-rsa
    echo PubkeyAcceptedAlgorithms +ssh-rsa >> /etc/ssh/sshd_config
    systemctl restart sshd

    echo --- Setting Internet access via eth1...
    ip route del default
    /fabric/connect_edu.sh

    echo 
    ip route
    echo 
}

COMMAND="$1"
shift

case ${COMMAND} in
    (install|script|prepare|restore)
	"${COMMAND}" "$@";;
    *)
	echo "ERROR: invalid command ${COMMAND}" >& 2
	exit 254;;
esac