#!/bin/bash

# Enable logging
exec 3>&1 4>&2 >/tmp/postinst.log 2>&1

echo Running postinst... 
status_fail=0

apt update
apt install nodejs npm python3-paramiko python3-jinja2 python3-netaddr nano sshpass -y
npm install -g newman
pip3 install paramiko-expect ansible --break-system-packages

echo "----------------------------------"
echo "Starting instance configuration..."
echo "----------------------------------"

# Install .bashrc
echo Updating .bashrc...
cp /fortipoc/.bashrc ~
if [ -f /fortipoc/.hol_sdwan ]
then
  echo This is an SDWAN-only instance.
  export HOL_SDWAN=1
  echo export HOL_SDWAN=1 >> ~/.bashrc
fi

# Install ssh_config
echo Updating ssh_config...
cp /fortipoc/ssh_config ~/.ssh/config
echo UserKnownHostsFile /dev/null >> /etc/ssh/ssh_config
echo StrictHostKeyChecking no >> /etc/ssh/ssh_config

# Download HoL files and unpack the Deployer
echo Downloading HoL files and installing the Deployer...
cd /fortipoc
./setup_deployer.sh

# Check boot status and license of FGTs
retries=19
cd /fortipoc/autodeploy
until ./check_devices.py || [ $retries -le 0 ]
do
    echo "Some devices didn't finish booting (retries left = $retries)"
    sleep 30
    ((retries--))
done

if [ $retries -gt 0 ];
then

  echo "--------------------------------"
  echo "Calling configure_instance.sh..."
  echo "--------------------------------"  

  # Finalize instance configuration
  ./configure_instance.sh || status_fail=1

  [ $status_fail -eq 0 ] || echo -e "\n\033[0;31mFATAL:\033[0m Some instance configuration tasks failed!"

else
  echo -e "\n\033[0;31mFATAL:\033[0m Some devices didn't finish booting or do not have valid licenses!"
  status_fail=1
fi

if [ $status_fail -eq 0 ];
then
  echo "This instance has been successfully configured."
else
  echo "Please check the above logs, fix the problem(s) and then manually run './configure_instance.sh' to complete instance configuration!"
fi

# Restore stdin/stderr
exec 1>&3 2>&4

exit $status_fail
