#!/bin/bash

# Enable logging
exec 3>&1 4>&2 >/tmp/postinst.log 2>&1

echo Running postinst... 
status_fail=0

apt update
apt install nodejs npm python3-paramiko python3-jinja2 nano -y
npm install -g newman
pip3 install paramiko-expect --break-system-packages

echo "----------------------------------"
echo "Starting instance configuration..."
echo "----------------------------------"

# Download HoL tenants and scripts
cd /fortipoc
wget -O hol-3.0.zip https://github.com/fortinet-solutions-cse/postman_collections/archive/refs/tags/hol-3.0.zip

# Unpack the Deployer
shopt -s dotglob
tar xfz solution-deployer.tgz
solution-deployer/install.sh autodeploy
unzip -o hol-3.0.zip 'postman_collections-hol-3.0/hol/scripts/*' 
unzip -o hol-3.0.zip 'postman_collections-hol-3.0/hol/tenants/*'
mv postman_collections-hol-3.0/hol/scripts/* autodeploy
mv postman_collections-hol-3.0/hol/tenants/* autodeploy/tenants
tar xfz hol_files.tgz -C autodeploy
rm -rf solution-deployer
rm -rf postman_collections-hol-3.0
rm hol-3.0.zip

# Check boot status and license of FGTs
retries=19
cd /fortipoc/autodeploy
until ./check_devices.py || [ $retries -le 0 ]
do
    echo "Some devices didn't finish booting (retries left = $retries)"
    sleep 30
    ((retries--))
done

if [ $retries -gt 0 ];
then

  echo "--------------------------------"
  echo "Calling configure_instance.sh..."
  echo "--------------------------------"  

  # Finalize instance configuration
  ./configure_instance.sh || status_fail=1

  [ $status_fail -eq 0 ] || echo -e "\n\033[0;31mFATAL:\033[0m Some instance configuration tasks failed!"

else
  echo -e "\n\033[0;31mFATAL:\033[0m Some devices didn't finish booting or do not have valid licenses!"
  status_fail=1
fi

if [ $status_fail -eq 0 ];
then
  echo "This instance has been successfully configured."
else
  echo "Please check the above logs, fix the problem(s) and then manually run './configure_instance.sh' to complete instance configuration!"
fi

# Restore stdin/stderr
exec 1>&3 2>&4

exit $status_fail
