---
fmg_host: 192.168.0.15
fmg_user: admin
fmg_password: fortinet
fmg_adom: CustomerU

postman_collection: tenants/shared/Managed_SDWAN_7_4_x.postman.json
default_skip_tags: lab,west-east,bor

fgfm_ip: 192.168.0.15
fgt_user: admin
fgt_password: fortinet

sites:
  site1-1:
    ip: 192.168.0.31
  site1-2:
    ip: 192.168.0.32
  site2-1:
    ip: 192.168.0.33
  site1-H1:
    ip: 192.168.0.41
  site1-H2:
    ip: 192.168.0.42
  site2-H1:
    ip: 192.168.0.43

tasks:
  - name: Create Foundation
    type: postman
    folder: Foundation
    tag: foundation
  - name: Import Project Template (dyn_bgp only)
    type: cli_templates
    src: tenants/CustomerU/Project.dyn_bgp.j2
    rename: Project
    tag: lab
  - name: Import Project Template (mixed)
    type: cli_templates
    src: tenants/CustomerU/Project.mixed.j2
    rename: Project
    tag: mixed
  - name: Import Jinja CLI Templates
    type: cli_templates
    src: tenants/shared/sdwan-advpn-reference-hol-3.0/dynamic-bgp-on-lo/*.j2
    tag: foundation
  - name: Create CLI Template Groups
    type: postman
    folder: Create CLI Template Groups
    tag: foundation
  - name: Finalize Foundation
    type: postman
    folder: Finalize Foundation
    vars: tenants/CustomerU/postman.vars.yaml
    tag: foundation
  - name: Fine-tune SD-WAN
    type: postman
    folder: Fine-tune SD-WAN
    tag: fine-tune-sdwan
  - name: Import SSL Decryption Certificate
    type: cli_templates
    src: tenants/CustomerU/05-Edge-Cert.j2
    tag: fine-tune-sase
  - name: Fine-tune for Uni-SASE
    type: postman
    folder: Fine-tune Uni-SASE
    tag: fine-tune-sase
  - name: Create Model Devices - West-East
    type: model_devices
    src: tenants/CustomerU/inventory.CustomerU.csv
    fos: 7.4
    tag: model-devices,west-east
  - name: Create Model Devices - West-only
    type: model_devices
    src: tenants/CustomerU/inventory.CustomerU_West.csv
    fos: 7.4
    tag: model-devices,west-only
  - name: Additional Post-Deployment Tasks
    type: postman
    folder: Post-Deployment
    tag: post-deploy
  - name: Install Model Devices (Staging) - West-East
    type: postman
    folder: CustomerU - Staging
    tag: staging,west-east
  - name: Install Model Devices (Staging) - West-only
    type: postman
    folder: CustomerU - Staging West
    tag: staging,west-only
  - name: Onboard Devices - West-East
    type: onboard
    src: tenants/CustomerU/inventory.CustomerU.csv
    monitor: yes
    tag: onboard,west-east
  - name: Onboard Devices - West-only
    type: onboard
    src: tenants/CustomerU/inventory.CustomerU_West.csv
    monitor: yes
    retry: yes
    tag: onboard,west-only
  - name: Deploy BOR
    type: postman
    folder: CustomerU - BOR
    tag: bor,west-only