---
fmg_host: 192.168.0.15
fmg_user: admin
fmg_adom: CustomerU

postman_collection: tenants/shared/Managed_SDWAN_8_0_x.postman.json
default_skip_tags: west-only,bor,fine-tune-sase

fgfm_ip: 192.168.0.15
fgt_user: admin

sites:
  site1-1:
    ip: 192.168.0.31
  site1-2:
    ip: 192.168.0.32
  site2-1:
    ip: 192.168.0.33
  site1-H1:
    ip: 192.168.0.41
  site1-H2:
    ip: 192.168.0.42
  site2-H1:
    ip: 192.168.0.43

tasks:
  - name: Create Foundation
    type: postman
    folder: Foundation
    tag: foundation
  - name: Create Variables
    type: postman
    folder: CustomerU - Variables
    tag: foundation    
  - name: Import Project Template (dyn_bgp only)
    type: cli_templates
    src: tenants/CustomerU/Project.dyn_bgp.j2
    rename: 00-Project
  - name: Import Project Template (mixed)
    type: cli_templates
    src: tenants/CustomerU/Project.mixed.j2
    rename: 00-Project
    tag: mixed
  - name: Import Jinja CLI Templates
    type: cli_templates
    src: tenants/shared/sdwan-advpn-reference-hol-5.0/dynamic-bgp-on-lo/*.j2
    tag: foundation
  - name: Create CLI Template Groups
    type: postman
    folder: Create CLI Template Groups
    tag: foundation
  - name: Finalize Foundation
    type: postman
    folder: CustomerU - Finalize
    vars: tenants/CustomerU/postman.vars.yaml
    tag: foundation
  - name: Fine-tune for Uni-SASE
    type: postman
    folder: CustomerU - Fine-tune Uni-SASE
    tag: fine-tune-sase
  - name: Create Model Devices - West-East
    type: model_devices
    src: tenants/CustomerU/inventory.CustomerU.csv
    fos: 8.0
    admin_user: admin
    tag: west-east
  - name: Create Model Devices - West-only
    type: model_devices
    src: tenants/CustomerU/inventory.CustomerU_West.csv
    fos: 8.0
    admin_user: admin
    tag: west-only 
  - name: Install Model Devices (Staging) - West-East
    type: postman
    folder: CustomerU - Staging
    tag: west-east
  - name: Install Model Devices (Staging) - West-only
    type: postman
    folder: CustomerU - Staging West
    tag: west-only
  - name: Onboard Devices - West-East
    type: onboard
    src: tenants/CustomerU/inventory.CustomerU.csv
    monitor: yes
    retry: yes
    tag: west-east
  - name: Onboard Devices - West-only
    type: onboard
    src: tenants/CustomerU/inventory.CustomerU_West.csv
    monitor: yes
    retry: yes
    tag: west-only
  - name: Deploy BOR
    type: postman
    folder: CustomerU - BOR
    tag: bor