---
fmg_host: 192.168.0.15
fmg_user: admin
fmg_adom: CustomerC

postman_collection: tenants/shared/Deployment_Guide_SDWAN_8_0_x.postman.json

fgfm_ip: 192.168.0.15
fgt_user: admin

sites:
  site1-1:
    ip: 192.168.0.31
  site1-2:
    ip: 192.168.0.32
  site2-1:
    ip: 192.168.0.33
  site1-H1:
    ip: 192.168.0.41
  site1-H2:
    ip: 192.168.0.42
  site2-H1:
    ip: 192.168.0.43

tasks:
  - name: Create Foundation
    type: postman
    folder: Foundation
  - name: Import Project Template
    type: cli_templates
    rename: Project
    src: tenants/shared/sdwan-advpn-reference-hol-5.0/dynamic-bgp-on-lo/projects/Project.dualreg.cert.j2
  - name: Import Jinja CLI Templates
    type: cli_templates
    src: tenants/shared/sdwan-advpn-reference-hol-5.0/dynamic-bgp-on-lo/*.j2
  - name: Create CLI Template Groups
    type: postman
    folder: Create CLI Template Groups
  - name: Create Template Groups
    type: postman
    folder: Create Template Groups
  - name: Create Device Blueprints
    type: postman
    folder: Device Blueprints
  - name: Create Model Devices
    type: model_devices
    src: tenants/DeploymentGuide/inventory.CustomerC.csv
    admin_user: admin
  - name: Install Model Devices (Staging)
    type: postman
    folder: Staging
  - name: Onboard Devices
    type: onboard
    src: tenants/DeploymentGuide/inventory.CustomerC.csv
